apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-{{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-{{ .Values.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-{{ .Values.name }}
    spec:
      containers:
      - image: nginx
        name: {{ .Values.name }}
        resources: {}
status: {}
